version: '3.5'

services:
  news: 
    build:
      context: ./news
    volumes:
    - "./news:/app"

  headpage:
    build:
      context: ./headpage
    volumes:
    - "./headpage:/app"
  
  about:
    build:
      context: ./about
    volumes:
    - "./about:/app"

  pymgur:
    build:
      context: ./pymgur
    volumes:
    - "./pymgur:/app"

  center:
    build:
      context: ./center
    volumes:
    - "./center:/app"
    ports:
    - "5000:5000"
    environment:
    - "PYMGUR=pymgur"
    - "NEWS=news"
    - "HEADPAGE=headpage"
    - "ABOUT=about"
