version: '3.5'

services:
  news: 
    build:
      context: ./novosti
    volumes:
    - "./novosti:/app"

  headpage:
    build:
      context: ./naslovnica
    volumes:
    - "./naslovnica:/app"
  
  pymgur:
    build:
      context: ./pymgur
    volumes:
    - "./pymgur:/app"

  center:
    build:
      context: ./center
    volumes:
    - "./center:/app"
    ports:
    - "5000:5000"
    environment:
    - "PYMGUR=pymgur"
    - "NEWS=news"
    - "HEADPAGE=headpage"
    
